kind: Deployment
apiVersion: apps/v1
metadata:
  name: servicelogin
  namespace: test 
  labels:
    app: servicelogin
    app.kubernetes.io/component: servicelogin
    app.kubernetes.io/instance: servicelogin
    app.kubernetes.io/name: servicelogin
    app.kubernetes.io/part-of: service-login-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: servicelogin
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: servicelogin
        deployment: servicelogin
    spec:
      containers:
        - name: servicelogin
          image: >-
            quay.io/vishwanath_puranik/slogin
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
